#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVEDRI_FINAL_PROJECT
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HotelDeLuna")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_Admin(tbl_Admin instance);
    partial void Updatetbl_Admin(tbl_Admin instance);
    partial void Deletetbl_Admin(tbl_Admin instance);
    partial void Inserttbl_Staff(tbl_Staff instance);
    partial void Updatetbl_Staff(tbl_Staff instance);
    partial void Deletetbl_Staff(tbl_Staff instance);
    partial void Inserttbl_account(tbl_account instance);
    partial void Updatetbl_account(tbl_account instance);
    partial void Deletetbl_account(tbl_account instance);
    partial void Inserttbl_Room(tbl_Room instance);
    partial void Updatetbl_Room(tbl_Room instance);
    partial void Deletetbl_Room(tbl_Room instance);
    partial void Inserttbl_CheckIn(tbl_CheckIn instance);
    partial void Updatetbl_CheckIn(tbl_CheckIn instance);
    partial void Deletetbl_CheckIn(tbl_CheckIn instance);
    partial void Inserttbl_CheckOut(tbl_CheckOut instance);
    partial void Updatetbl_CheckOut(tbl_CheckOut instance);
    partial void Deletetbl_CheckOut(tbl_CheckOut instance);
    partial void Inserttbl_Guest(tbl_Guest instance);
    partial void Updatetbl_Guest(tbl_Guest instance);
    partial void Deletetbl_Guest(tbl_Guest instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::EVEDRI_FINAL_PROJECT.Properties.Settings.Default.HotelDeLunaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_Admin> tbl_Admins
		{
			get
			{
				return this.GetTable<tbl_Admin>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Staff> tbl_Staffs
		{
			get
			{
				return this.GetTable<tbl_Staff>();
			}
		}
		
		public System.Data.Linq.Table<tbl_account> tbl_accounts
		{
			get
			{
				return this.GetTable<tbl_account>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Room> tbl_Rooms
		{
			get
			{
				return this.GetTable<tbl_Room>();
			}
		}
		
		public System.Data.Linq.Table<tbl_CheckIn> tbl_CheckIns
		{
			get
			{
				return this.GetTable<tbl_CheckIn>();
			}
		}
		
		public System.Data.Linq.Table<tbl_CheckOut> tbl_CheckOuts
		{
			get
			{
				return this.GetTable<tbl_CheckOut>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Guest> tbl_Guests
		{
			get
			{
				return this.GetTable<tbl_Guest>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_admin_Guest")]
		public ISingleResult<SP_admin_GuestResult> SP_admin_Guest()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_admin_GuestResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_User_Craete_Guest")]
		public int SP_User_Craete_Guest([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string fname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string lname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string phoneNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string email)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fname, lname, phoneNumber, email);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_admin_staff")]
		public ISingleResult<SP_admin_staffResult> SP_admin_staff()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_admin_staffResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_User_Transact_Rooms")]
		public int SP_User_Transact_Rooms([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> guestId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string room_type, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string room_number, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string guestCount)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), guestId, room_type, room_number, guestCount);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_User_Transact_CheckOut")]
		public int SP_User_Transact_CheckOut([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> guestId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> checkOut, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DaysCount", DbType="NVarChar(30)")] string daysCount)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), guestId, checkOut, daysCount);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_User_Transact_CheckIn")]
		public int SP_User_Transact_CheckIn([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> guestId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(10,2)")] System.Nullable<decimal> totalAmount, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> checkIn_Date)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), guestId, totalAmount, checkIn_Date);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_user_checkOutView")]
		public ISingleResult<SP_user_checkOutViewResult> SP_user_checkOutView()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_user_checkOutViewResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_user_SettleMent")]
		public ISingleResult<SP_user_SettleMentResult> SP_user_SettleMent([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> guestId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), guestId);
			return ((ISingleResult<SP_user_SettleMentResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_admin_Records")]
		public ISingleResult<SP_admin_RecordsResult> SP_admin_Records()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_admin_RecordsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_user_ViewForClean")]
		public ISingleResult<SP_user_ViewForCleanResult> SP_user_ViewForClean()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_user_ViewForCleanResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_user_CleanSettleMent")]
		public ISingleResult<SP_user_CleanSettleMentResult> SP_user_CleanSettleMent([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> guestId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), guestId);
			return ((ISingleResult<SP_user_CleanSettleMentResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Admin_DelEmployee")]
		public int SP_Admin_DelEmployee([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> emp_Id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), emp_Id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Admin_addUser")]
		public int SP_Admin_addUser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string passsword)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username, passsword);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Admin_DelUser")]
		public int SP_Admin_DelUser([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Admin_ViewAccounts")]
		public ISingleResult<SP_Admin_ViewAccountsResult> SP_Admin_ViewAccounts()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_Admin_ViewAccountsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Admin_addEmployee")]
		public int SP_Admin_addEmployee([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string fname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string lname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string position, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string phone, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string address)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fname, lname, position, phone, email, address);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Admin")]
	public partial class tbl_Admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _adminId;
		
		private string _admin_User;
		
		private string _admin_Pass;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnadminIdChanging(int value);
    partial void OnadminIdChanged();
    partial void Onadmin_UserChanging(string value);
    partial void Onadmin_UserChanged();
    partial void Onadmin_PassChanging(string value);
    partial void Onadmin_PassChanged();
    #endregion
		
		public tbl_Admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adminId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int adminId
		{
			get
			{
				return this._adminId;
			}
			set
			{
				if ((this._adminId != value))
				{
					this.OnadminIdChanging(value);
					this.SendPropertyChanging();
					this._adminId = value;
					this.SendPropertyChanged("adminId");
					this.OnadminIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_User", DbType="NVarChar(50)")]
		public string admin_User
		{
			get
			{
				return this._admin_User;
			}
			set
			{
				if ((this._admin_User != value))
				{
					this.Onadmin_UserChanging(value);
					this.SendPropertyChanging();
					this._admin_User = value;
					this.SendPropertyChanged("admin_User");
					this.Onadmin_UserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_Pass", DbType="NVarChar(50)")]
		public string admin_Pass
		{
			get
			{
				return this._admin_Pass;
			}
			set
			{
				if ((this._admin_Pass != value))
				{
					this.Onadmin_PassChanging(value);
					this.SendPropertyChanging();
					this._admin_Pass = value;
					this.SendPropertyChanged("admin_Pass");
					this.Onadmin_PassChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Staff")]
	public partial class tbl_Staff : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _staff_Id;
		
		private string _firstName;
		
		private string _lastName;
		
		private string _position;
		
		private string _phoneNumber;
		
		private string _email;
		
		private string _homeAddress;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onstaff_IdChanging(int value);
    partial void Onstaff_IdChanged();
    partial void OnfirstNameChanging(string value);
    partial void OnfirstNameChanged();
    partial void OnlastNameChanging(string value);
    partial void OnlastNameChanged();
    partial void OnpositionChanging(string value);
    partial void OnpositionChanged();
    partial void OnphoneNumberChanging(string value);
    partial void OnphoneNumberChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnhomeAddressChanging(string value);
    partial void OnhomeAddressChanged();
    #endregion
		
		public tbl_Staff()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staff_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int staff_Id
		{
			get
			{
				return this._staff_Id;
			}
			set
			{
				if ((this._staff_Id != value))
				{
					this.Onstaff_IdChanging(value);
					this.SendPropertyChanging();
					this._staff_Id = value;
					this.SendPropertyChanged("staff_Id");
					this.Onstaff_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string firstName
		{
			get
			{
				return this._firstName;
			}
			set
			{
				if ((this._firstName != value))
				{
					this.OnfirstNameChanging(value);
					this.SendPropertyChanging();
					this._firstName = value;
					this.SendPropertyChanged("firstName");
					this.OnfirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string lastName
		{
			get
			{
				return this._lastName;
			}
			set
			{
				if ((this._lastName != value))
				{
					this.OnlastNameChanging(value);
					this.SendPropertyChanging();
					this._lastName = value;
					this.SendPropertyChanged("lastName");
					this.OnlastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_position", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string position
		{
			get
			{
				return this._position;
			}
			set
			{
				if ((this._position != value))
				{
					this.OnpositionChanging(value);
					this.SendPropertyChanging();
					this._position = value;
					this.SendPropertyChanged("position");
					this.OnpositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phoneNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string phoneNumber
		{
			get
			{
				return this._phoneNumber;
			}
			set
			{
				if ((this._phoneNumber != value))
				{
					this.OnphoneNumberChanging(value);
					this.SendPropertyChanging();
					this._phoneNumber = value;
					this.SendPropertyChanged("phoneNumber");
					this.OnphoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_homeAddress", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string homeAddress
		{
			get
			{
				return this._homeAddress;
			}
			set
			{
				if ((this._homeAddress != value))
				{
					this.OnhomeAddressChanging(value);
					this.SendPropertyChanging();
					this._homeAddress = value;
					this.SendPropertyChanged("homeAddress");
					this.OnhomeAddressChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_account")]
	public partial class tbl_account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _acc_id;
		
		private string _acc_User;
		
		private string _acc_Pass;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onacc_idChanging(int value);
    partial void Onacc_idChanged();
    partial void Onacc_UserChanging(string value);
    partial void Onacc_UserChanged();
    partial void Onacc_PassChanging(string value);
    partial void Onacc_PassChanged();
    #endregion
		
		public tbl_account()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_acc_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int acc_id
		{
			get
			{
				return this._acc_id;
			}
			set
			{
				if ((this._acc_id != value))
				{
					this.Onacc_idChanging(value);
					this.SendPropertyChanging();
					this._acc_id = value;
					this.SendPropertyChanged("acc_id");
					this.Onacc_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_acc_User", DbType="NVarChar(50)")]
		public string acc_User
		{
			get
			{
				return this._acc_User;
			}
			set
			{
				if ((this._acc_User != value))
				{
					this.Onacc_UserChanging(value);
					this.SendPropertyChanging();
					this._acc_User = value;
					this.SendPropertyChanged("acc_User");
					this.Onacc_UserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_acc_Pass", DbType="NVarChar(50)")]
		public string acc_Pass
		{
			get
			{
				return this._acc_Pass;
			}
			set
			{
				if ((this._acc_Pass != value))
				{
					this.Onacc_PassChanging(value);
					this.SendPropertyChanging();
					this._acc_Pass = value;
					this.SendPropertyChanged("acc_Pass");
					this.Onacc_PassChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Rooms")]
	public partial class tbl_Room : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _room_Id;
		
		private string _room_type;
		
		private string _room_number;
		
		private string _personCount;
		
		private System.Nullable<int> _Guest_Id;
		
		private EntityRef<tbl_Guest> _tbl_Guest;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onroom_IdChanging(int value);
    partial void Onroom_IdChanged();
    partial void Onroom_typeChanging(string value);
    partial void Onroom_typeChanged();
    partial void Onroom_numberChanging(string value);
    partial void Onroom_numberChanged();
    partial void OnpersonCountChanging(string value);
    partial void OnpersonCountChanged();
    partial void OnGuest_IdChanging(System.Nullable<int> value);
    partial void OnGuest_IdChanged();
    #endregion
		
		public tbl_Room()
		{
			this._tbl_Guest = default(EntityRef<tbl_Guest>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int room_Id
		{
			get
			{
				return this._room_Id;
			}
			set
			{
				if ((this._room_Id != value))
				{
					this.Onroom_IdChanging(value);
					this.SendPropertyChanging();
					this._room_Id = value;
					this.SendPropertyChanged("room_Id");
					this.Onroom_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_type", DbType="NVarChar(50)")]
		public string room_type
		{
			get
			{
				return this._room_type;
			}
			set
			{
				if ((this._room_type != value))
				{
					this.Onroom_typeChanging(value);
					this.SendPropertyChanging();
					this._room_type = value;
					this.SendPropertyChanged("room_type");
					this.Onroom_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_number", DbType="NVarChar(30)")]
		public string room_number
		{
			get
			{
				return this._room_number;
			}
			set
			{
				if ((this._room_number != value))
				{
					this.Onroom_numberChanging(value);
					this.SendPropertyChanging();
					this._room_number = value;
					this.SendPropertyChanged("room_number");
					this.Onroom_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_personCount", DbType="NVarChar(30)")]
		public string personCount
		{
			get
			{
				return this._personCount;
			}
			set
			{
				if ((this._personCount != value))
				{
					this.OnpersonCountChanging(value);
					this.SendPropertyChanging();
					this._personCount = value;
					this.SendPropertyChanged("personCount");
					this.OnpersonCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guest_Id", DbType="Int")]
		public System.Nullable<int> Guest_Id
		{
			get
			{
				return this._Guest_Id;
			}
			set
			{
				if ((this._Guest_Id != value))
				{
					if (this._tbl_Guest.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGuest_IdChanging(value);
					this.SendPropertyChanging();
					this._Guest_Id = value;
					this.SendPropertyChanged("Guest_Id");
					this.OnGuest_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Guest_tbl_Room", Storage="_tbl_Guest", ThisKey="Guest_Id", OtherKey="Guest_Id", IsForeignKey=true)]
		public tbl_Guest tbl_Guest
		{
			get
			{
				return this._tbl_Guest.Entity;
			}
			set
			{
				tbl_Guest previousValue = this._tbl_Guest.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Guest.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Guest.Entity = null;
						previousValue.tbl_Rooms.Remove(this);
					}
					this._tbl_Guest.Entity = value;
					if ((value != null))
					{
						value.tbl_Rooms.Add(this);
						this._Guest_Id = value.Guest_Id;
					}
					else
					{
						this._Guest_Id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_Guest");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_CheckIn")]
	public partial class tbl_CheckIn : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _checkIn_Id;
		
		private System.Nullable<decimal> _Total_Amount;
		
		private System.Nullable<System.DateTime> _checkIn_date;
		
		private System.Nullable<int> _Guest_Id;
		
		private EntityRef<tbl_Guest> _tbl_Guest;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncheckIn_IdChanging(int value);
    partial void OncheckIn_IdChanged();
    partial void OnTotal_AmountChanging(System.Nullable<decimal> value);
    partial void OnTotal_AmountChanged();
    partial void OncheckIn_dateChanging(System.Nullable<System.DateTime> value);
    partial void OncheckIn_dateChanged();
    partial void OnGuest_IdChanging(System.Nullable<int> value);
    partial void OnGuest_IdChanged();
    #endregion
		
		public tbl_CheckIn()
		{
			this._tbl_Guest = default(EntityRef<tbl_Guest>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_checkIn_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int checkIn_Id
		{
			get
			{
				return this._checkIn_Id;
			}
			set
			{
				if ((this._checkIn_Id != value))
				{
					this.OncheckIn_IdChanging(value);
					this.SendPropertyChanging();
					this._checkIn_Id = value;
					this.SendPropertyChanged("checkIn_Id");
					this.OncheckIn_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_Amount", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Total_Amount
		{
			get
			{
				return this._Total_Amount;
			}
			set
			{
				if ((this._Total_Amount != value))
				{
					this.OnTotal_AmountChanging(value);
					this.SendPropertyChanging();
					this._Total_Amount = value;
					this.SendPropertyChanged("Total_Amount");
					this.OnTotal_AmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_checkIn_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> checkIn_date
		{
			get
			{
				return this._checkIn_date;
			}
			set
			{
				if ((this._checkIn_date != value))
				{
					this.OncheckIn_dateChanging(value);
					this.SendPropertyChanging();
					this._checkIn_date = value;
					this.SendPropertyChanged("checkIn_date");
					this.OncheckIn_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guest_Id", DbType="Int")]
		public System.Nullable<int> Guest_Id
		{
			get
			{
				return this._Guest_Id;
			}
			set
			{
				if ((this._Guest_Id != value))
				{
					if (this._tbl_Guest.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGuest_IdChanging(value);
					this.SendPropertyChanging();
					this._Guest_Id = value;
					this.SendPropertyChanged("Guest_Id");
					this.OnGuest_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Guest_tbl_CheckIn", Storage="_tbl_Guest", ThisKey="Guest_Id", OtherKey="Guest_Id", IsForeignKey=true)]
		public tbl_Guest tbl_Guest
		{
			get
			{
				return this._tbl_Guest.Entity;
			}
			set
			{
				tbl_Guest previousValue = this._tbl_Guest.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Guest.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Guest.Entity = null;
						previousValue.tbl_CheckIns.Remove(this);
					}
					this._tbl_Guest.Entity = value;
					if ((value != null))
					{
						value.tbl_CheckIns.Add(this);
						this._Guest_Id = value.Guest_Id;
					}
					else
					{
						this._Guest_Id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_Guest");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_CheckOut")]
	public partial class tbl_CheckOut : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _checkOut_Id;
		
		private System.Nullable<System.DateTime> _checkOut_date;
		
		private string _DaysCount;
		
		private System.Nullable<int> _Guest_Id;
		
		private EntityRef<tbl_Guest> _tbl_Guest;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncheckOut_IdChanging(int value);
    partial void OncheckOut_IdChanged();
    partial void OncheckOut_dateChanging(System.Nullable<System.DateTime> value);
    partial void OncheckOut_dateChanged();
    partial void OnDaysCountChanging(string value);
    partial void OnDaysCountChanged();
    partial void OnGuest_IdChanging(System.Nullable<int> value);
    partial void OnGuest_IdChanged();
    #endregion
		
		public tbl_CheckOut()
		{
			this._tbl_Guest = default(EntityRef<tbl_Guest>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_checkOut_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int checkOut_Id
		{
			get
			{
				return this._checkOut_Id;
			}
			set
			{
				if ((this._checkOut_Id != value))
				{
					this.OncheckOut_IdChanging(value);
					this.SendPropertyChanging();
					this._checkOut_Id = value;
					this.SendPropertyChanged("checkOut_Id");
					this.OncheckOut_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_checkOut_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> checkOut_date
		{
			get
			{
				return this._checkOut_date;
			}
			set
			{
				if ((this._checkOut_date != value))
				{
					this.OncheckOut_dateChanging(value);
					this.SendPropertyChanging();
					this._checkOut_date = value;
					this.SendPropertyChanged("checkOut_date");
					this.OncheckOut_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaysCount", DbType="NVarChar(30)")]
		public string DaysCount
		{
			get
			{
				return this._DaysCount;
			}
			set
			{
				if ((this._DaysCount != value))
				{
					this.OnDaysCountChanging(value);
					this.SendPropertyChanging();
					this._DaysCount = value;
					this.SendPropertyChanged("DaysCount");
					this.OnDaysCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guest_Id", DbType="Int")]
		public System.Nullable<int> Guest_Id
		{
			get
			{
				return this._Guest_Id;
			}
			set
			{
				if ((this._Guest_Id != value))
				{
					if (this._tbl_Guest.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGuest_IdChanging(value);
					this.SendPropertyChanging();
					this._Guest_Id = value;
					this.SendPropertyChanged("Guest_Id");
					this.OnGuest_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Guest_tbl_CheckOut", Storage="_tbl_Guest", ThisKey="Guest_Id", OtherKey="Guest_Id", IsForeignKey=true)]
		public tbl_Guest tbl_Guest
		{
			get
			{
				return this._tbl_Guest.Entity;
			}
			set
			{
				tbl_Guest previousValue = this._tbl_Guest.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Guest.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Guest.Entity = null;
						previousValue.tbl_CheckOuts.Remove(this);
					}
					this._tbl_Guest.Entity = value;
					if ((value != null))
					{
						value.tbl_CheckOuts.Add(this);
						this._Guest_Id = value.Guest_Id;
					}
					else
					{
						this._Guest_Id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_Guest");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Guest")]
	public partial class tbl_Guest : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Guest_Id;
		
		private string _firstName;
		
		private string _lastName;
		
		private string _phoneNumber;
		
		private string _email;
		
		private string _RoomType;
		
		private string _RoomNo;
		
		private string _PersonCount;
		
		private string _CheckIn;
		
		private string _CheckOut;
		
		private string _NoOfDays;
		
		private string _IsSettled;
		
		private string _IsClean;
		
		private EntitySet<tbl_Room> _tbl_Rooms;
		
		private EntitySet<tbl_CheckIn> _tbl_CheckIns;
		
		private EntitySet<tbl_CheckOut> _tbl_CheckOuts;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGuest_IdChanging(int value);
    partial void OnGuest_IdChanged();
    partial void OnfirstNameChanging(string value);
    partial void OnfirstNameChanged();
    partial void OnlastNameChanging(string value);
    partial void OnlastNameChanged();
    partial void OnphoneNumberChanging(string value);
    partial void OnphoneNumberChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnRoomTypeChanging(string value);
    partial void OnRoomTypeChanged();
    partial void OnRoomNoChanging(string value);
    partial void OnRoomNoChanged();
    partial void OnPersonCountChanging(string value);
    partial void OnPersonCountChanged();
    partial void OnCheckInChanging(string value);
    partial void OnCheckInChanged();
    partial void OnCheckOutChanging(string value);
    partial void OnCheckOutChanged();
    partial void OnNoOfDaysChanging(string value);
    partial void OnNoOfDaysChanged();
    partial void OnIsSettledChanging(string value);
    partial void OnIsSettledChanged();
    partial void OnIsCleanChanging(string value);
    partial void OnIsCleanChanged();
    #endregion
		
		public tbl_Guest()
		{
			this._tbl_Rooms = new EntitySet<tbl_Room>(new Action<tbl_Room>(this.attach_tbl_Rooms), new Action<tbl_Room>(this.detach_tbl_Rooms));
			this._tbl_CheckIns = new EntitySet<tbl_CheckIn>(new Action<tbl_CheckIn>(this.attach_tbl_CheckIns), new Action<tbl_CheckIn>(this.detach_tbl_CheckIns));
			this._tbl_CheckOuts = new EntitySet<tbl_CheckOut>(new Action<tbl_CheckOut>(this.attach_tbl_CheckOuts), new Action<tbl_CheckOut>(this.detach_tbl_CheckOuts));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guest_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Guest_Id
		{
			get
			{
				return this._Guest_Id;
			}
			set
			{
				if ((this._Guest_Id != value))
				{
					this.OnGuest_IdChanging(value);
					this.SendPropertyChanging();
					this._Guest_Id = value;
					this.SendPropertyChanged("Guest_Id");
					this.OnGuest_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string firstName
		{
			get
			{
				return this._firstName;
			}
			set
			{
				if ((this._firstName != value))
				{
					this.OnfirstNameChanging(value);
					this.SendPropertyChanging();
					this._firstName = value;
					this.SendPropertyChanged("firstName");
					this.OnfirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string lastName
		{
			get
			{
				return this._lastName;
			}
			set
			{
				if ((this._lastName != value))
				{
					this.OnlastNameChanging(value);
					this.SendPropertyChanging();
					this._lastName = value;
					this.SendPropertyChanged("lastName");
					this.OnlastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phoneNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string phoneNumber
		{
			get
			{
				return this._phoneNumber;
			}
			set
			{
				if ((this._phoneNumber != value))
				{
					this.OnphoneNumberChanging(value);
					this.SendPropertyChanging();
					this._phoneNumber = value;
					this.SendPropertyChanged("phoneNumber");
					this.OnphoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomType", DbType="NVarChar(30)")]
		public string RoomType
		{
			get
			{
				return this._RoomType;
			}
			set
			{
				if ((this._RoomType != value))
				{
					this.OnRoomTypeChanging(value);
					this.SendPropertyChanging();
					this._RoomType = value;
					this.SendPropertyChanged("RoomType");
					this.OnRoomTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomNo", DbType="NVarChar(30)")]
		public string RoomNo
		{
			get
			{
				return this._RoomNo;
			}
			set
			{
				if ((this._RoomNo != value))
				{
					this.OnRoomNoChanging(value);
					this.SendPropertyChanging();
					this._RoomNo = value;
					this.SendPropertyChanged("RoomNo");
					this.OnRoomNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonCount", DbType="NVarChar(30)")]
		public string PersonCount
		{
			get
			{
				return this._PersonCount;
			}
			set
			{
				if ((this._PersonCount != value))
				{
					this.OnPersonCountChanging(value);
					this.SendPropertyChanging();
					this._PersonCount = value;
					this.SendPropertyChanged("PersonCount");
					this.OnPersonCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckIn", DbType="NVarChar(30)")]
		public string CheckIn
		{
			get
			{
				return this._CheckIn;
			}
			set
			{
				if ((this._CheckIn != value))
				{
					this.OnCheckInChanging(value);
					this.SendPropertyChanging();
					this._CheckIn = value;
					this.SendPropertyChanged("CheckIn");
					this.OnCheckInChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckOut", DbType="NVarChar(30)")]
		public string CheckOut
		{
			get
			{
				return this._CheckOut;
			}
			set
			{
				if ((this._CheckOut != value))
				{
					this.OnCheckOutChanging(value);
					this.SendPropertyChanging();
					this._CheckOut = value;
					this.SendPropertyChanged("CheckOut");
					this.OnCheckOutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoOfDays", DbType="NVarChar(30)")]
		public string NoOfDays
		{
			get
			{
				return this._NoOfDays;
			}
			set
			{
				if ((this._NoOfDays != value))
				{
					this.OnNoOfDaysChanging(value);
					this.SendPropertyChanging();
					this._NoOfDays = value;
					this.SendPropertyChanged("NoOfDays");
					this.OnNoOfDaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSettled", DbType="NVarChar(30)")]
		public string IsSettled
		{
			get
			{
				return this._IsSettled;
			}
			set
			{
				if ((this._IsSettled != value))
				{
					this.OnIsSettledChanging(value);
					this.SendPropertyChanging();
					this._IsSettled = value;
					this.SendPropertyChanged("IsSettled");
					this.OnIsSettledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsClean", DbType="NVarChar(30)")]
		public string IsClean
		{
			get
			{
				return this._IsClean;
			}
			set
			{
				if ((this._IsClean != value))
				{
					this.OnIsCleanChanging(value);
					this.SendPropertyChanging();
					this._IsClean = value;
					this.SendPropertyChanged("IsClean");
					this.OnIsCleanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Guest_tbl_Room", Storage="_tbl_Rooms", ThisKey="Guest_Id", OtherKey="Guest_Id")]
		public EntitySet<tbl_Room> tbl_Rooms
		{
			get
			{
				return this._tbl_Rooms;
			}
			set
			{
				this._tbl_Rooms.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Guest_tbl_CheckIn", Storage="_tbl_CheckIns", ThisKey="Guest_Id", OtherKey="Guest_Id")]
		public EntitySet<tbl_CheckIn> tbl_CheckIns
		{
			get
			{
				return this._tbl_CheckIns;
			}
			set
			{
				this._tbl_CheckIns.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Guest_tbl_CheckOut", Storage="_tbl_CheckOuts", ThisKey="Guest_Id", OtherKey="Guest_Id")]
		public EntitySet<tbl_CheckOut> tbl_CheckOuts
		{
			get
			{
				return this._tbl_CheckOuts;
			}
			set
			{
				this._tbl_CheckOuts.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Rooms(tbl_Room entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Guest = this;
		}
		
		private void detach_tbl_Rooms(tbl_Room entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Guest = null;
		}
		
		private void attach_tbl_CheckIns(tbl_CheckIn entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Guest = this;
		}
		
		private void detach_tbl_CheckIns(tbl_CheckIn entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Guest = null;
		}
		
		private void attach_tbl_CheckOuts(tbl_CheckOut entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Guest = this;
		}
		
		private void detach_tbl_CheckOuts(tbl_CheckOut entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Guest = null;
		}
	}
	
	public partial class SP_admin_GuestResult
	{
		
		private int _Id_no;
		
		private string _Full_Name;
		
		private string _Phone_Number;
		
		private string _Email;
		
		public SP_admin_GuestResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Id no]", Storage="_Id_no", DbType="Int NOT NULL")]
		public int Id_no
		{
			get
			{
				return this._Id_no;
			}
			set
			{
				if ((this._Id_no != value))
				{
					this._Id_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Full Name]", Storage="_Full_Name", DbType="NVarChar(101) NOT NULL", CanBeNull=false)]
		public string Full_Name
		{
			get
			{
				return this._Full_Name;
			}
			set
			{
				if ((this._Full_Name != value))
				{
					this._Full_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Phone Number]", Storage="_Phone_Number", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Phone_Number
		{
			get
			{
				return this._Phone_Number;
			}
			set
			{
				if ((this._Phone_Number != value))
				{
					this._Phone_Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
	}
	
	public partial class SP_admin_staffResult
	{
		
		private int _staff_id;
		
		private string _Full_Name;
		
		private string _Position;
		
		private string _Phone_Number;
		
		private string _Email;
		
		private string _Home_Address;
		
		public SP_admin_staffResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staff_id", DbType="Int NOT NULL")]
		public int staff_id
		{
			get
			{
				return this._staff_id;
			}
			set
			{
				if ((this._staff_id != value))
				{
					this._staff_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Full Name]", Storage="_Full_Name", DbType="NVarChar(101) NOT NULL", CanBeNull=false)]
		public string Full_Name
		{
			get
			{
				return this._Full_Name;
			}
			set
			{
				if ((this._Full_Name != value))
				{
					this._Full_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Position", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Position
		{
			get
			{
				return this._Position;
			}
			set
			{
				if ((this._Position != value))
				{
					this._Position = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Phone Number]", Storage="_Phone_Number", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Phone_Number
		{
			get
			{
				return this._Phone_Number;
			}
			set
			{
				if ((this._Phone_Number != value))
				{
					this._Phone_Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Home Address]", Storage="_Home_Address", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Home_Address
		{
			get
			{
				return this._Home_Address;
			}
			set
			{
				if ((this._Home_Address != value))
				{
					this._Home_Address = value;
				}
			}
		}
	}
	
	public partial class SP_user_checkOutViewResult
	{
		
		private int _Id_no;
		
		private string _Full_Name;
		
		private string _Phone_Number;
		
		private string _Email;
		
		private string _RoomType;
		
		private string _RoomNo;
		
		private string _CheckIn;
		
		private string _CheckOut;
		
		public SP_user_checkOutViewResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Id no]", Storage="_Id_no", DbType="Int NOT NULL")]
		public int Id_no
		{
			get
			{
				return this._Id_no;
			}
			set
			{
				if ((this._Id_no != value))
				{
					this._Id_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Full Name]", Storage="_Full_Name", DbType="NVarChar(101) NOT NULL", CanBeNull=false)]
		public string Full_Name
		{
			get
			{
				return this._Full_Name;
			}
			set
			{
				if ((this._Full_Name != value))
				{
					this._Full_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Phone Number]", Storage="_Phone_Number", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Phone_Number
		{
			get
			{
				return this._Phone_Number;
			}
			set
			{
				if ((this._Phone_Number != value))
				{
					this._Phone_Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomType", DbType="NVarChar(30)")]
		public string RoomType
		{
			get
			{
				return this._RoomType;
			}
			set
			{
				if ((this._RoomType != value))
				{
					this._RoomType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomNo", DbType="NVarChar(30)")]
		public string RoomNo
		{
			get
			{
				return this._RoomNo;
			}
			set
			{
				if ((this._RoomNo != value))
				{
					this._RoomNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckIn", DbType="NVarChar(30)")]
		public string CheckIn
		{
			get
			{
				return this._CheckIn;
			}
			set
			{
				if ((this._CheckIn != value))
				{
					this._CheckIn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckOut", DbType="NVarChar(30)")]
		public string CheckOut
		{
			get
			{
				return this._CheckOut;
			}
			set
			{
				if ((this._CheckOut != value))
				{
					this._CheckOut = value;
				}
			}
		}
	}
	
	public partial class SP_user_SettleMentResult
	{
		
		private int _Id_no;
		
		private string _Full_Name;
		
		private string _Phone_Number;
		
		private string _Email;
		
		private string _RoomType;
		
		private string _RoomNo;
		
		private string _CheckIn;
		
		private string _CheckOut;
		
		public SP_user_SettleMentResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Id no]", Storage="_Id_no", DbType="Int NOT NULL")]
		public int Id_no
		{
			get
			{
				return this._Id_no;
			}
			set
			{
				if ((this._Id_no != value))
				{
					this._Id_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Full Name]", Storage="_Full_Name", DbType="NVarChar(101) NOT NULL", CanBeNull=false)]
		public string Full_Name
		{
			get
			{
				return this._Full_Name;
			}
			set
			{
				if ((this._Full_Name != value))
				{
					this._Full_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Phone Number]", Storage="_Phone_Number", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Phone_Number
		{
			get
			{
				return this._Phone_Number;
			}
			set
			{
				if ((this._Phone_Number != value))
				{
					this._Phone_Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomType", DbType="NVarChar(30)")]
		public string RoomType
		{
			get
			{
				return this._RoomType;
			}
			set
			{
				if ((this._RoomType != value))
				{
					this._RoomType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomNo", DbType="NVarChar(30)")]
		public string RoomNo
		{
			get
			{
				return this._RoomNo;
			}
			set
			{
				if ((this._RoomNo != value))
				{
					this._RoomNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckIn", DbType="NVarChar(30)")]
		public string CheckIn
		{
			get
			{
				return this._CheckIn;
			}
			set
			{
				if ((this._CheckIn != value))
				{
					this._CheckIn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckOut", DbType="NVarChar(30)")]
		public string CheckOut
		{
			get
			{
				return this._CheckOut;
			}
			set
			{
				if ((this._CheckOut != value))
				{
					this._CheckOut = value;
				}
			}
		}
	}
	
	public partial class SP_admin_RecordsResult
	{
		
		private int _Id_no;
		
		private string _Full_Name;
		
		private string _Phone_Number;
		
		private string _Email;
		
		private string _RoomType;
		
		private string _RoomNo;
		
		private string _PersonCount;
		
		private string _CheckIn;
		
		private string _CheckOut;
		
		private string _NoOfDays;
		
		private string _IsSettled;
		
		private string _cleaned;
		
		public SP_admin_RecordsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Id no]", Storage="_Id_no", DbType="Int NOT NULL")]
		public int Id_no
		{
			get
			{
				return this._Id_no;
			}
			set
			{
				if ((this._Id_no != value))
				{
					this._Id_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Full Name]", Storage="_Full_Name", DbType="NVarChar(101) NOT NULL", CanBeNull=false)]
		public string Full_Name
		{
			get
			{
				return this._Full_Name;
			}
			set
			{
				if ((this._Full_Name != value))
				{
					this._Full_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Phone Number]", Storage="_Phone_Number", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Phone_Number
		{
			get
			{
				return this._Phone_Number;
			}
			set
			{
				if ((this._Phone_Number != value))
				{
					this._Phone_Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomType", DbType="NVarChar(30)")]
		public string RoomType
		{
			get
			{
				return this._RoomType;
			}
			set
			{
				if ((this._RoomType != value))
				{
					this._RoomType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomNo", DbType="NVarChar(30)")]
		public string RoomNo
		{
			get
			{
				return this._RoomNo;
			}
			set
			{
				if ((this._RoomNo != value))
				{
					this._RoomNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonCount", DbType="NVarChar(30)")]
		public string PersonCount
		{
			get
			{
				return this._PersonCount;
			}
			set
			{
				if ((this._PersonCount != value))
				{
					this._PersonCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckIn", DbType="NVarChar(30)")]
		public string CheckIn
		{
			get
			{
				return this._CheckIn;
			}
			set
			{
				if ((this._CheckIn != value))
				{
					this._CheckIn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckOut", DbType="NVarChar(30)")]
		public string CheckOut
		{
			get
			{
				return this._CheckOut;
			}
			set
			{
				if ((this._CheckOut != value))
				{
					this._CheckOut = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoOfDays", DbType="NVarChar(30)")]
		public string NoOfDays
		{
			get
			{
				return this._NoOfDays;
			}
			set
			{
				if ((this._NoOfDays != value))
				{
					this._NoOfDays = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSettled", DbType="NVarChar(30)")]
		public string IsSettled
		{
			get
			{
				return this._IsSettled;
			}
			set
			{
				if ((this._IsSettled != value))
				{
					this._IsSettled = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cleaned", DbType="NVarChar(30)")]
		public string cleaned
		{
			get
			{
				return this._cleaned;
			}
			set
			{
				if ((this._cleaned != value))
				{
					this._cleaned = value;
				}
			}
		}
	}
	
	public partial class SP_user_ViewForCleanResult
	{
		
		private int _Id_no;
		
		private string _Full_Name;
		
		private string _Phone_Number;
		
		private string _Email;
		
		private string _RoomType;
		
		private string _RoomNo;
		
		private string _CheckIn;
		
		private string _CheckOut;
		
		private string _IsSettled;
		
		private string _Cleaned;
		
		public SP_user_ViewForCleanResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Id no]", Storage="_Id_no", DbType="Int NOT NULL")]
		public int Id_no
		{
			get
			{
				return this._Id_no;
			}
			set
			{
				if ((this._Id_no != value))
				{
					this._Id_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Full Name]", Storage="_Full_Name", DbType="NVarChar(101) NOT NULL", CanBeNull=false)]
		public string Full_Name
		{
			get
			{
				return this._Full_Name;
			}
			set
			{
				if ((this._Full_Name != value))
				{
					this._Full_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Phone Number]", Storage="_Phone_Number", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Phone_Number
		{
			get
			{
				return this._Phone_Number;
			}
			set
			{
				if ((this._Phone_Number != value))
				{
					this._Phone_Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomType", DbType="NVarChar(30)")]
		public string RoomType
		{
			get
			{
				return this._RoomType;
			}
			set
			{
				if ((this._RoomType != value))
				{
					this._RoomType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomNo", DbType="NVarChar(30)")]
		public string RoomNo
		{
			get
			{
				return this._RoomNo;
			}
			set
			{
				if ((this._RoomNo != value))
				{
					this._RoomNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckIn", DbType="NVarChar(30)")]
		public string CheckIn
		{
			get
			{
				return this._CheckIn;
			}
			set
			{
				if ((this._CheckIn != value))
				{
					this._CheckIn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckOut", DbType="NVarChar(30)")]
		public string CheckOut
		{
			get
			{
				return this._CheckOut;
			}
			set
			{
				if ((this._CheckOut != value))
				{
					this._CheckOut = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSettled", DbType="NVarChar(30)")]
		public string IsSettled
		{
			get
			{
				return this._IsSettled;
			}
			set
			{
				if ((this._IsSettled != value))
				{
					this._IsSettled = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cleaned", DbType="NVarChar(30)")]
		public string Cleaned
		{
			get
			{
				return this._Cleaned;
			}
			set
			{
				if ((this._Cleaned != value))
				{
					this._Cleaned = value;
				}
			}
		}
	}
	
	public partial class SP_user_CleanSettleMentResult
	{
		
		private int _Id_no;
		
		private string _Full_Name;
		
		private string _Phone_Number;
		
		private string _Email;
		
		private string _RoomType;
		
		private string _RoomNo;
		
		private string _CheckIn;
		
		private string _CheckOut;
		
		public SP_user_CleanSettleMentResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Id no]", Storage="_Id_no", DbType="Int NOT NULL")]
		public int Id_no
		{
			get
			{
				return this._Id_no;
			}
			set
			{
				if ((this._Id_no != value))
				{
					this._Id_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Full Name]", Storage="_Full_Name", DbType="NVarChar(101) NOT NULL", CanBeNull=false)]
		public string Full_Name
		{
			get
			{
				return this._Full_Name;
			}
			set
			{
				if ((this._Full_Name != value))
				{
					this._Full_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Phone Number]", Storage="_Phone_Number", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Phone_Number
		{
			get
			{
				return this._Phone_Number;
			}
			set
			{
				if ((this._Phone_Number != value))
				{
					this._Phone_Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomType", DbType="NVarChar(30)")]
		public string RoomType
		{
			get
			{
				return this._RoomType;
			}
			set
			{
				if ((this._RoomType != value))
				{
					this._RoomType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomNo", DbType="NVarChar(30)")]
		public string RoomNo
		{
			get
			{
				return this._RoomNo;
			}
			set
			{
				if ((this._RoomNo != value))
				{
					this._RoomNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckIn", DbType="NVarChar(30)")]
		public string CheckIn
		{
			get
			{
				return this._CheckIn;
			}
			set
			{
				if ((this._CheckIn != value))
				{
					this._CheckIn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckOut", DbType="NVarChar(30)")]
		public string CheckOut
		{
			get
			{
				return this._CheckOut;
			}
			set
			{
				if ((this._CheckOut != value))
				{
					this._CheckOut = value;
				}
			}
		}
	}
	
	public partial class SP_Admin_ViewAccountsResult
	{
		
		private int _acc_id;
		
		private string _Username;
		
		private string _Password;
		
		public SP_Admin_ViewAccountsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_acc_id", DbType="Int NOT NULL")]
		public int acc_id
		{
			get
			{
				return this._acc_id;
			}
			set
			{
				if ((this._acc_id != value))
				{
					this._acc_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
